# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3eab31347b1810d194b7b46534ce78c55644f7f37aa9ae7014f424c187c0a71820df1f21fd0703165363364966aca1384770dfd2cad43157d18104fb0bc28f3

test:
  secret_key_base: 4a55c89465a4f71f6d925239d2d8b4eec6ecded5524a7b8366573cd11dd0b2d7c4a0ecb2ef3e7f0718b1e42bd7323eda37f33c00e14cfb6fd58d16e26a8e53c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
